name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        run: |
          mkdir -p $RUNNER_TEMP
          tar \
            --dereference --hard-dereference \
            --directory . \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .

      - name: Debug Artifact
        run: |
          ls -lah $RUNNER_TEMP
          if [ ! -f "$RUNNER_TEMP/artifact.tar" ]; then
            echo "Artifact not found"; exit 1;
          fi

      - name: Upload Pages artifact
        if: success()  # Ensure the previous steps succeed
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: $RUNNER_TEMP/artifact.tar  # Ensure this path is valid
          retention-days: 1
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
